### ISSUE TITLE
An error occurred！

### ISSUE THREAD

**Issue by HppZ** [dustinmoris/DustedCodes#11]
![default](https://cloud.githubusercontent.com/assets/12285582/13904476/f59a6a3e-eedc-11e5-8eb3-70430185e60f.png)

Another question: 
I created a new ASP.NET MVC5 project with VS2015, and its folder structure is much different with yours.  Where is connectionStrings setting in your project?

I am new to ASP.NET.
Thank you!

**Comment by dustinmoris** [comment]
Hi,

My blog does not have a connection string because it does not require a database. It has been designed to load blog articles from the local file system. I store my blog posts as markdown files in App_Data\Articles\ and they get converted into .html files during build time and the live website just outputs the raw html from the converted files.

The folder structure is slightly different because I renamed a couple folders and deleted everything which I did not need.

To get it running try the following:
- Place at least 1 *.md file into the App_Data\Articles folder
- Build the project in release mode and restore all NuGet packages

This should work in theory... let me know how it goes.

The DustedCodes project is mainly designed to my own personal requirements. It is open source and you can copy ideas from it, but most likely will not 100% match your own requirements. Feel free to explore my structure and see how it works.

If there is an interest for a more generic reusable ASP.NET blog engine I might give it a shot some time. Let's see how it goes...

**Comment by HppZ** [comment]
Hi, that's very kind of you.

And I am very interested in ASP.NET because I want to build my own website.
Maybe you can write some tutorials about how to build a blog engine, I think that would be very helpful for beginners like me.
Thanks a lot.

**Comment by HppZ** [comment]
![error](https://cloud.githubusercontent.com/assets/12285582/16109434/52652220-33db-11e6-8364-3bc1e6ca7e19.png)

an error occured in release mode.

if in debug mode, it says "Holy crap, an internal error occurred!", I already put a markdown file in App_Data\Articles folder.
so what is wrong?

**Comment by HppZ** [comment]
I solved. :)

**Comment by dustinmoris** [comment]
Awesome, I just wanted to reply that I would have taken a loot at it tonight, but glad you figured it out :)
